nginx:
    image: manoj1992/nginx-lb:3.0
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    image: msanand/docker-workflow 
    links:
        - redis
    ports:
        - "8080"
node2:
    image: msanand/docker-workflow
    links:
        - redis
    ports:
        - "8080"
node3:
    image: msanand/docker-workflow
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
